### PR TITLE
CDP 1415

### PR DESCRIPTION
**Pull request by mrewers**
Populate newly created video unit with the tags from it's parent project.

### CODE REVIEW

**Comment by mrewers** [comment]
Hold review - reworking to move tag connection into the unit tree building process at project creation.

**Comment by terriregan** [comment]
Has this been updated per our conversation from yesterday?

**Comment by mrewers** [comment]
@terriregan not yet, hence the message above. I'll let you know when I push the update.

**Comment by terriregan** [comment]
After reviewing, I think that I should probably have built out the full tree on creation so we don't have to pass unit values around to be used to save unit section.  This will need to be modified to upload file and then update db for each file instead of only updating db after all files are uploaded.  That way we can save successful files if one errors.

**Pull request merged**
